FROM centos/systemd

RUN yum -y remove java***

# Install packages
RUN yum -y install openssh-server sudo nano epel-release openssl certmonger java-11-openjdk-devel.x86_64 1:11.0.19.0.7-1.el7_9 git; systemctl enable sshd.service

# Enable root and pos accounts
RUN echo 'root:33103255235331325230' | chpasswd
RUN adduser pos && \
	echo 'pos:ol2432sn324231024113310' | chpasswd && \
	usermod -aG wheel pos
RUN adduser jenkins && \
	echo 'jenkins:ol2432sn324231024113310' | chpasswd && \
	usermod -aG wheel jenkins

# Configure SSHD
RUN mkdir -p /var/run/sshd ; chmod -rx /var/run/sshd

# http://stackoverflow.com/questions/2419412/ssh-connection-stop-at-debug1-ssh2-msg-kexinit-sent
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key

# Bad security, add a user and sudo instead!
RUN sed -ri 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config

# http://stackoverflow.com/questions/18173889/cannot-access-centos-sshd-on-docker
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

# Deploy ssh keys
RUN mkdir /root/.ssh/ && \
	echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlftC6XGmPJ4EsqT8UgJDgYNuTUvkIg57mOvY2pcDvrMkuns6mmRb7vbbac8JFfCLFK07AaHY/hkysmu/8zqSN4QLlm9IGvShOtzzK+QG0JdQwLflItj14THCYcJXr+D/ZUaU7eFrjDE8AoYj0HIABa0zQBNjU8+1VF0ceiwxga7UMgad+QhZ8kEkxBt24a0rh5TLufdd81oE1jDbIi7i9G2VaHMOqdwNjNcDtaH7Lrgnn/hG70qAGM4essJhSEEehWnAkZaY+3rOEiLtOBhLgIWt5yWIyApZ/S/KVnNJia3xHMSxv1rR76HiN+F1RRg/y91UN1rBxxkZ40qhPDfiKqHcwUqgGDtDDtLLPNLBXoXPqLLlqOnzk74eYdILYuuhmQyL0saONANovX+EvZcaa9Nc0o9uGWdPHO/sjgUKWKwY0iRxsGPqxpDbwlsoT0msfs5QE+BT7whujx7ZhN+/bKjxshJnJ5nZRFJHQTOIDpocxSA1H/ZtqQqoUKJvzsgU=" > ~/.ssh/authorized_keys && \
	chmod 700 ~/.ssh && \
	chmod 600 ~/.ssh/authorized_keys

RUN mkdir /home/pos/.ssh/ && \
	echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlftC6XGmPJ4EsqT8UgJDgYNuTUvkIg57mOvY2pcDvrMkuns6mmRb7vbbac8JFfCLFK07AaHY/hkysmu/8zqSN4QLlm9IGvShOtzzK+QG0JdQwLflItj14THCYcJXr+D/ZUaU7eFrjDE8AoYj0HIABa0zQBNjU8+1VF0ceiwxga7UMgad+QhZ8kEkxBt24a0rh5TLufdd81oE1jDbIi7i9G2VaHMOqdwNjNcDtaH7Lrgnn/hG70qAGM4essJhSEEehWnAkZaY+3rOEiLtOBhLgIWt5yWIyApZ/S/KVnNJia3xHMSxv1rR76HiN+F1RRg/y91UN1rBxxkZ40qhPDfiKqHcwUqgGDtDDtLLPNLBXoXPqLLlqOnzk74eYdILYuuhmQyL0saONANovX+EvZcaa9Nc0o9uGWdPHO/sjgUKWKwY0iRxsGPqxpDbwlsoT0msfs5QE+BT7whujx7ZhN+/bKjxshJnJ5nZRFJHQTOIDpocxSA1H/ZtqQqoUKJvzsgU=" > /home/pos/.ssh/authorized_keys && \
	chmod 700 /home/pos/.ssh && \
	chmod 600 /home/pos/.ssh/authorized_keys && \
	chown -R pos:pos /home/pos/.ssh/

RUN mkdir /home/jenkins/.ssh/ && \
	echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlftC6XGmPJ4EsqT8UgJDgYNuTUvkIg57mOvY2pcDvrMkuns6mmRb7vbbac8JFfCLFK07AaHY/hkysmu/8zqSN4QLlm9IGvShOtzzK+QG0JdQwLflItj14THCYcJXr+D/ZUaU7eFrjDE8AoYj0HIABa0zQBNjU8+1VF0ceiwxga7UMgad+QhZ8kEkxBt24a0rh5TLufdd81oE1jDbIi7i9G2VaHMOqdwNjNcDtaH7Lrgnn/hG70qAGM4essJhSEEehWnAkZaY+3rOEiLtOBhLgIWt5yWIyApZ/S/KVnNJia3xHMSxv1rR76HiN+F1RRg/y91UN1rBxxkZ40qhPDfiKqHcwUqgGDtDDtLLPNLBXoXPqLLlqOnzk74eYdILYuuhmQyL0saONANovX+EvZcaa9Nc0o9uGWdPHO/sjgUKWKwY0iRxsGPqxpDbwlsoT0msfs5QE+BT7whujx7ZhN+/bKjxshJnJ5nZRFJHQTOIDpocxSA1H/ZtqQqoUKJvzsgU=" > /home/jenkins/.ssh/authorized_keys && \
	chmod 700 /home/jenkins/.ssh && \
	chmod 600 /home/jenkins/.ssh/authorized_keys && \
	chown -R jenkins:jenkins /home/jenkins/.ssh/

# Configure pos and jenkins
RUN bash -c 'echo "pos ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'
RUN bash -c 'echo "jenkins ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'

EXPOSE 22

CMD ["/usr/sbin/init"]