FROM centos/systemd

RUN yum -y remove java***

# Install packages
RUN yum -y install openssh-server sudo nano epel-release openssl certmonger java-11-openjdk-devel.x86_64 1:11.0.19.0.7-1.el7_9 git; systemctl enable sshd.service

# Enable root and pos accounts
RUN echo 'root:Welcome@123' | chpasswd
RUN adduser pos && \
	echo 'pos:Welcome@123' | chpasswd && \
	usermod -aG wheel pos
RUN adduser jenkins && \
	echo 'jenkins:Welcome@123' | chpasswd && \
	usermod -aG wheel jenkins

# Configure SSHD
RUN mkdir -p /var/run/sshd ; chmod -rx /var/run/sshd

# http://stackoverflow.com/questions/2419412/ssh-connection-stop-at-debug1-ssh2-msg-kexinit-sent
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key

# Bad security, add a user and sudo instead!
RUN sed -ri 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config

# http://stackoverflow.com/questions/18173889/cannot-access-centos-sshd-on-docker
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

# Deploy ssh keys for root
RUN mkdir /root/.ssh/
COPY ssh-keys/id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 700 /root/.ssh && \
	chmod 600 /root/.ssh/authorized_keys

# Deploy ssh keys for pos
RUN mkdir /home/pos/.ssh/
COPY ssh-keys/id_rsa.pub /home/pos/.ssh/authorized_keys
RUN	chmod 700 /home/pos/.ssh && \
	chmod 600 /home/pos/.ssh/authorized_keys && \
	chown -R pos:pos /home/pos/.ssh/

# Deploy ssh keys for jenkins
RUN mkdir /home/jenkins/.ssh/
COPY ssh-keys/id_rsa.pub /home/jenkins/.ssh/authorized_keys
RUN	chmod 700 /home/jenkins/.ssh && \
	chmod 600 /home/jenkins/.ssh/authorized_keys && \
	chown -R jenkins:jenkins /home/jenkins/.ssh/


# Configure pos and jenkins
RUN bash -c 'echo "pos ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'
RUN bash -c 'echo "jenkins ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'

EXPOSE 22

CMD ["/usr/sbin/init"]