FROM jrei/systemd-ubuntu

RUN apt-get update && \
    apt-get install -y openssh-server sudo nano openssl certmonger git openjdk-11-jdk && \
    systemctl enable ssh

# Enable root and pos accounts
RUN echo 'root:Welcome@123' | chpasswd
RUN adduser --disabled-login --home /home/pos --gecos "" pos && \
	echo 'pos:Welcome@123' | chpasswd && \
	usermod -aG sudo pos
RUN adduser --disabled-login --home /home/jenkins --gecos "" jenkins && \
	echo 'jenkins:Welcome@123' | chpasswd && \
	usermod -aG sudo jenkins

# Configure SSHD
RUN mkdir -p /var/run/sshd ; chmod -rx /var/run/sshd

# Bad security, add a user and sudo instead!
RUN sed -ri 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config

# http://stackoverflow.com/questions/18173889/cannot-access-centos-sshd-on-docker
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

RUN mkdir /root/.ssh/
COPY ssh-keys/id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 700 /root/.ssh && \
	chmod 600 /root/.ssh/authorized_keys

# Deploy ssh keys for pos
RUN mkdir /home/pos/.ssh/
COPY ssh-keys/id_rsa.pub /home/pos/.ssh/authorized_keys
RUN	chmod 700 /home/pos/.ssh && \
	chmod 600 /home/pos/.ssh/authorized_keys && \
	chown -R pos:pos /home/pos/.ssh/

# Deploy ssh keys for jenkins
RUN mkdir /home/jenkins/.ssh/
COPY ssh-keys/id_rsa.pub /home/jenkins/.ssh/authorized_keys
RUN	chmod 700 /home/jenkins/.ssh && \
	chmod 600 /home/jenkins/.ssh/authorized_keys && \
	chown -R jenkins:jenkins /home/jenkins/.ssh/


# Configure pos and jenkins
RUN bash -c 'echo "pos ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'
RUN bash -c 'echo "jenkins ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'

EXPOSE 22

CMD ["/lib/systemd/systemd"]