apiVersion: v1
kind: Pod
metadata:
  name: nginx
  #namespace: <your_namespace_name>
  #annotations: <Fill_In_Anootations>
  labels:
    app: nginx
    version: "1.25.1"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80