apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # Dummy name
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  azureDisk: # Legacy
    cachingMode: ReadWrite
    diskName: demo
    diskURI: /subscriptions/29f4fd39-55c5-46f0-9e75-d9d16df4f544/resourceGroups/MC_Training_demo_centralindia/providers/Microsoft.Compute/disks/demo
    kind: Managed
    readOnly: false
  #csi:
  #  driver: disk.csi.azure.com
  #  readOnly: false
  #  volumeHandle: /subscriptions/29f4fd39-55c5-46f0-9e75-d9d16df4f544/resourceGroups/MC_Training_demo_centralindia/providers/Microsoft.Compute/disks/demo
  #  volumeAttributes:
  #    fsType: ext4
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-azuredisk
    namespace: default

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-azuredisk
  storageClassName: manual
  volumeMode: Filesystem

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: nginx
    name: mypod
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - name: azure
        mountPath: /azure-disk
  volumes:
    - name: azure
      persistentVolumeClaim:
        claimName: pvc-azuredisk