# Dynamic Provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
  #namespace: <your_namespace_name>
spec:
  #storageClassName: "managed-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: nginx
    name: mypod
    resources:
      requests:   # For Scheduler - Helps to find a Node
        cpu: 100m
        memory: 128Mi
      limits:    # This is the upper limit. Resource usage can't go beyond this.
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - name: azure
        mountPath: /azure-disk
  volumes:
    - name: azure
      persistentVolumeClaim:
        claimName: pvc-azuredisk
