---
 - hosts: all
   tasks:
      - name: "Install Nginx"
        package:
          name: nginx
          state: latest

      - name: "Start Nginx"
        service:
          name: nginx
          state: restarted
